### ISSUE TITLE
./build.sh failing with "not a bzip2 file"

### ISSUE THREAD

**Issue by dma156** [Jalle19/libreelec-docker-deluge#17]
Just followed the steps. Ran into this issue during the ./build.sh step. LibreELEC 9.95.2, Kodi 19.0

```
Setting up intltool (0.51.0-5ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Processing triggers for ca-certificates (20210119~18.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   302  100   302    0     0    327      0 --:--:-- --:--:-- --:--:--   326
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command '/bin/sh -c apt-get -y update &&   apt-get -y install --no-install-recommends curl     pyth       on     python-twisted     python-openssl     python-setuptools     gettext     intltool     python-xdg            python-chardet     geoip-database     python-geoip     python-libtorrent     python-mako &&   cd /u       sr/src &&   curl -L $DELUGE_URL | tar -C /usr/src -xjf - &&   cd /usr/src/deluge-* &&   python setup.py        build &&   python setup.py install &&   rm -rf     /usr/local/bin/deluge     /usr/local/bin/deluge-gtk            /usr/src     /usr/local/lib/python*/site-packages/deluge-*-py*.egg/share/pixmaps     /usr/local/li       b/python*/site-packages/deluge-*-py*.egg/share/man     /usr/local/lib/python*/site-packages/deluge-*-py       *.egg/deluge/ui/gtkui &&   rm -rf   /var/lib/apt/lists/*   /root/.cache   /tmp/*' returned a non-zero c       ode: 2
"docker tag" requires exactly 2 arguments.
See 'docker tag --help'.

Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE

```

**Comment by Jalle19** [comment]
Looks like they've changed the packaging.

**Comment by Jalle19** [comment]
@danielma82 can you try this branch instead: https://github.com/Jalle19/libreelec-docker-deluge/pull/18 ?

**Comment by dma156** [comment]
Wasn't able to git checkout due to no git on LibreELEC, used wget to grab the zip of the branch and ran it. 
A bunch of errors came up, here's just the last bit 

```
creating /usr/local/share/applications
copying deluge/ui/data/share/applications/deluge.desktop -> /usr/local/share/applications
creating /usr/local/share/appdata
copying deluge/ui/data/share/appdata/deluge.appdata.xml -> /usr/local/share/appdata
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying deluge.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying deluge.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying deluge.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying deluge.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying deluge.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying deluge.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
deluge.__pycache__.decorators.cpython-38: module MAY be using inspect.stack
deluge.__pycache__.log.cpython-38: module references __file__
deluge.__pycache__.log.cpython-38: module MAY be using inspect.stack
deluge.__pycache__.log.cpython-38: module MAY be using inspect.trace
deluge.ui.__pycache__.ui_entry.cpython-38: module references __file__
deluge.ui.console.__pycache__.__init__.cpython-38: module references __path__
creating dist
creating 'dist/deluge-2.0.3-py3.8.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing deluge-2.0.3-py3.8.egg
creating /usr/local/lib/python3.8/dist-packages/deluge-2.0.3-py3.8.egg
Extracting deluge-2.0.3-py3.8.egg to /usr/local/lib/python3.8/dist-packages
Adding deluge 2.0.3 to easy-install.pth file
Installing deluge-console script to /usr/local/bin
Installing deluge-web script to /usr/local/bin
Installing deluged script to /usr/local/bin
Installing deluge script to /usr/local/bin
Installing deluge-gtk script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/deluge-2.0.3-py3.8.egg
Processing dependencies for deluge==2.0.3
Searching for zope.interface
Reading https://pypi.org/simple/zope.interface/
Downloading https://files.pythonhosted.org/packages/ae/58/e0877f58daa69126a5fb325d6df92b20b77431cd281e189c5ec42b722f58/zope.interface-5.4.0.tar.gz#sha256=5dba5f530fec3f0988d83b78cc591b58c0b6eb8431a85edd1569a0539a8a5a0e
Best match: zope.interface 5.4.0
Processing zope.interface-5.4.0.tar.gz
Writing /tmp/easy_install-hckcp2hw/zope.interface-5.4.0/setup.cfg
Running zope.interface-5.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hckcp2hw/zope.interface-5.4.0/egg-dist-tmp-dizbci7g
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'benchmarks'
creating /usr/local/lib/python3.8/dist-packages/zope.interface-5.4.0-py3.8-linux-armv7l.egg
Extracting zope.interface-5.4.0-py3.8-linux-armv7l.egg to /usr/local/lib/python3.8/dist-packages
Adding zope.interface 5.4.0 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/zope.interface-5.4.0-py3.8-linux-armv7l.egg
Searching for twisted[tls]>=17.1
Reading https://pypi.org/simple/twisted/
Downloading https://files.pythonhosted.org/packages/f2/16/3eb9c66a7bfb5220c7bcbaaac33d359fe8a157b028959cd210983749b2e0/Twisted-21.2.0-py3-none-any.whl#sha256=aab38085ea6cda5b378b519a0ec99986874921ee8881318626b0a3414bb2631e
Best match: Twisted 21.2.0
Processing Twisted-21.2.0-py3-none-any.whl
Installing Twisted-21.2.0-py3-none-any.whl to /usr/local/lib/python3.8/dist-packages
Adding Twisted 21.2.0 to easy-install.pth file
Installing cftp script to /usr/local/bin
Installing ckeygen script to /usr/local/bin
Installing conch script to /usr/local/bin
Installing mailmail script to /usr/local/bin
Installing pyhtmlizer script to /usr/local/bin
Installing tkconch script to /usr/local/bin
Installing trial script to /usr/local/bin
Installing twist script to /usr/local/bin
Installing twistd script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/Twisted-21.2.0-py3.8.egg
Searching for six
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl#sha256=8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced
Best match: six 1.15.0
Processing six-1.15.0-py2.py3-none-any.whl
Installing six-1.15.0-py2.py3-none-any.whl to /usr/local/lib/python3.8/dist-packages
Adding six 1.15.0 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/six-1.15.0-py3.8.egg
Searching for setproctitle
Reading https://pypi.org/simple/setproctitle/
Downloading https://files.pythonhosted.org/packages/a1/7f/a1d4f4c7b66f0fc02f35dc5c85f45a8b4e4a7988357a29e61c14e725ef86/setproctitle-1.2.2.tar.gz#sha256=7dfb472c8852403d34007e01d6e3c68c57eb66433fb8a5c77b13b89a160d97df
Best match: setproctitle 1.2.2
Processing setproctitle-1.2.2.tar.gz
Writing /tmp/easy_install-30bsc1u3/setproctitle-1.2.2/setup.cfg
Running setproctitle-1.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-30bsc1u3/setproctitle-1.2.2/egg-dist-tmp-kbghyg3r
warning: no files found matching 'Makefile'
zip_safe flag not set; analyzing archive contents...
__pycache__.setproctitle.cpython-38: module references __file__
creating /usr/local/lib/python3.8/dist-packages/setproctitle-1.2.2-py3.8-linux-armv7l.egg
Extracting setproctitle-1.2.2-py3.8-linux-armv7l.egg to /usr/local/lib/python3.8/dist-packages
Adding setproctitle 1.2.2 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/setproctitle-1.2.2-py3.8-linux-armv7l.egg
Searching for rencode
Reading https://pypi.org/simple/rencode/
Downloading https://files.pythonhosted.org/packages/3a/fb/3c03dbe4438dd596e1378b5299990b81041739658a76e0f4a301eded67f4/rencode-1.0.6.tar.gz#sha256=2586435c4ea7d45f74e26765ad33d75309de7cf47c4d762e8efabd39905c0718
Best match: rencode 1.0.6
Processing rencode-1.0.6.tar.gz
Writing /tmp/easy_install-w2taor4x/rencode-1.0.6/setup.cfg
Running rencode-1.0.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-w2taor4x/rencode-1.0.6/egg-dist-tmp-t14m_uql
zip_safe flag not set; analyzing archive contents...
rencode.__pycache__._rencode.cpython-38: module references __file__
creating /usr/local/lib/python3.8/dist-packages/rencode-1.0.6-py3.8-linux-armv7l.egg
Extracting rencode-1.0.6-py3.8-linux-armv7l.egg to /usr/local/lib/python3.8/dist-packages
Adding rencode 1.0.6 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/rencode-1.0.6-py3.8-linux-armv7l.egg
Searching for pyxdg
Reading https://pypi.org/simple/pyxdg/
Downloading https://files.pythonhosted.org/packages/ea/13/de39ddf4f9f9cea0c7684cd54a50d79c97ea99c9f6aed798fd13d0bd4609/pyxdg-0.27-py2.py3-none-any.whl#sha256=2d6701ab7c74bbab8caa6a95e0a0a129b1643cf6c298bf7c569adec06d0709a0
Best match: pyxdg 0.27
Processing pyxdg-0.27-py2.py3-none-any.whl
Installing pyxdg-0.27-py2.py3-none-any.whl to /usr/local/lib/python3.8/dist-packages
Adding pyxdg 0.27 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/pyxdg-0.27-py3.8.egg
Searching for pyopenssl
Reading https://pypi.org/simple/pyopenssl/
Downloading https://files.pythonhosted.org/packages/b2/5e/06351ede29fd4899782ad335c2e02f1f862a887c20a3541f17c3fa1a3525/pyOpenSSL-20.0.1-py2.py3-none-any.whl#sha256=818ae18e06922c066f777a33f1fca45786d85edfe71cd043de6379337a7f274b
Best match: pyOpenSSL 20.0.1
Processing pyOpenSSL-20.0.1-py2.py3-none-any.whl
Installing pyOpenSSL-20.0.1-py2.py3-none-any.whl to /usr/local/lib/python3.8/dist-packages
Adding pyOpenSSL 20.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/pyOpenSSL-20.0.1-py3.8.egg
Searching for pyasn1
Reading https://pypi.org/simple/pyasn1/
Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl#sha256=39c7e2ec30515947ff4e87fb6f456dfc6e84857d34be479c9d4a4ba4bf46aa5d
Best match: pyasn1 0.4.8
Processing pyasn1-0.4.8-py2.py3-none-any.whl
Installing pyasn1-0.4.8-py2.py3-none-any.whl to /usr/local/lib/python3.8/dist-packages
Adding pyasn1 0.4.8 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/pyasn1-0.4.8-py3.8.egg
Searching for pillow
Reading https://pypi.org/simple/pillow/
Downloading https://files.pythonhosted.org/packages/21/23/af6bac2a601be6670064a817273d4190b79df6f74d8012926a39bc7aa77f/Pillow-8.2.0.tar.gz#sha256=a787ab10d7bb5494e5f76536ac460741788f1fbce851068d73a87ca7c35fc3e1
Best match: Pillow 8.2.0
Processing Pillow-8.2.0.tar.gz
Writing /tmp/easy_install-h6tcj6_a/Pillow-8.2.0/setup.cfg
Running Pillow-8.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-h6tcj6_a/Pillow-8.2.0/egg-dist-tmp-a87ibpsw
warning: no files found matching '*.c'
warning: no files found matching '*.h'
warning: no files found matching '*.sh'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.clang-format'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.readthedocs.yml'
warning: no previously-included files found matching 'codecov.yml'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
no previously-included directories found matching '.ci'


The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "/tmp/easy_install-h6tcj6_a/Pillow-8.2.0/setup.py", line 976, in <module>
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/tmp/easy_install-h6tcj6_a/Pillow-8.2.0/setup.py", line 788, in build_extensions
__main__.RequiredDependencyException: jpeg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-h6tcj6_a/Pillow-8.2.0/setup.py", line 1033, in <module>
__main__.RequiredDependencyException:

The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 558, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 450, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 740, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 784, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 781, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 712, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 923, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1191, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-h6tcj6_a/Pillow-8.2.0/setup.py", line 1033, in <module>
setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for jpeg,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n')
The command '/bin/sh -c apt-get -y update &&   apt-get -y install     curl     intltool     xz-utils     python3-libtorrent     python3-pip &&   pip3 install --upgrade pip &&   cd /usr/src &&   curl -L $DELUGE_URL | tar -C /usr/src -xJf - &&   cd /usr/src/deluge-* &&   python3 setup.py build &&   python3 setup.py install &&   rm -rf     /usr/local/bin/deluge     /usr/local/bin/deluge-gtk     /usr/src     /usr/local/lib/python*/dist-packages/deluge-*-py*.egg/deluge/ui/data/pixmaps     /usr/local/lib/python*/dist-packages/deluge-*-py*.egg/deluge/ui/gtk3 &&   apt-get -y remove python3-dev &&   apt-get -y autoremove &&   apt-get -y clean &&   rm -rf   /var/lib/apt/lists/*   /root/.cache   /tmp/*' returned a non-zero code: 1
"docker tag" requires exactly 2 arguments.
See 'docker tag --help'.

Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
```

**Comment by Jalle19** [comment]
I'm afraid this image only works on x86-64 platforms, at least at the moment.

**Comment by Jalle19** [comment]
Fixed the original issue in https://github.com/Jalle19/libreelec-docker-deluge/pull/19/commits/9cb1620dc5dd8e44102a55cedc97bf6f27740451
